### ISSUE TITLE
[FEAT] AddNoteView OCR 기능, 저장 기능 구현

### ISSUE THREAD

**Issue by SH0123** [ProjectInTheClass/ReadLog#17]
## 💡 Issue
AddNoteView의 핵심 기능인 OCR 기능과 기타 기능을 구현합니다

## 📝  todo
- [x] OCR 카메라 화면 구현
- [x] OCR 기능 구현
- [x] OCR 내용 TextEditor에 반영
- [x] 키보드 toolbar 설정

## 📸 Screenshot

<img width="299" alt="image" src="https://github.com/ProjectInTheClass/ReadLog/assets/26588989/63039b62-71fa-4259-9fa1-52f1f1d67176">
