### ISSUE TITLE
[FEAT] 검색 결과에서 선택한 책의 상세 정보 UI 구현

### ISSUE THREAD

**Issue by cactus-y** [ProjectInTheClass/ReadLog#25]
## 💡 Issue
검색을 한 뒤 선택한 책의 상세 정보를 보는 뷰의 UI를 구현합니다.
책 제목, 저자, 출판사, 다회독 정보를 보여주고, 책 소개를 보여준다.
책 소개 옆에는 네이버/알라딘의 구매 사이트 버튼이 있다. (뺄 수도 있음)
읽을 책 목록에 넣는 하트 버튼과, 읽고 있는 책 목록에 넣는 독서 시작 버튼이 있다.
만약 이미 읽고 있는 책의 정보를 보는 중이라면 버튼의 텍스트는 독서 시작 일자가 되고, 비활성화 된다.

## 📝  todo
- [x] 책의 정보를 보는 container view 생성
- [x] 책 소개 섹션 구현
- [x] 책의 판매 링크 버튼 구현
- [x] 찜 버튼과 독서 시작 (이미 읽고 있다면 독서 시작 일자) 버튼 구현

## 📸 Screenshot

![스크린샷 2023-11-20 오후 10 40 59](https://github.com/ProjectInTheClass/ReadLog/assets/55349972/1646ad0f-25fc-4852-b54f-d363a13efc49)
