### ISSUE TITLE
[FEAT] 홈화면 Carousel View + Coredata 구현

### ISSUE THREAD

**Issue by rfvtgbyh11** [ProjectInTheClass/ReadLog#39]
## 💡 Issue
홈화면을 시작할 때 데이터를 읽어와서 띄워주는 화면을 만든다.

## 📝  todo
- [x] CoreData를 이용해 ReadingList에 들어가 있는 데이터를 만든다.
- [x] ReadingList에 들어 있는 책들 데이터와 로그 데이터를 가져온다.
- [x] Carousel View를 이용해 책들을 하나씩 보고 관련된 로그를 띄운다.

## 📸 Screenshot

<img width="344" alt="스크린샷 2023-11-27 오전 11 00 29" src="https://github.com/ProjectInTheClass/ReadLog/assets/60872311/4836931a-7fe6-4f63-94ec-5db75607ee93">
