### ISSUE TITLE
[FEAT] CoreData attribute 추가, Add/Delete 구현

### ISSUE THREAD

**Issue by rfvtgbyh11** [ProjectInTheClass/ReadLog#46]
## 💡 Issue
CoreData의 마무리 작업을 한다.

## 📝  todo
- [x] attribute (1. recent 2. readingList에서 고정여부) 추가한다.
- [x] Add/Delete 가능한 함수 구현한다.
- [x] Preview data 조금 더 자세하게 완성한다.
