### ISSUE TITLE
[FEAT] 인상깊은 내용 작성 UI 구현

### ISSUE THREAD

**Issue by SH0123** [ProjectInTheClass/ReadLog#5]
## 💡 Issue
인상깊은 내용 작성 UI를 구현합니다.

## 📝  todo
- [ ] 스캔 버튼 구현
- [ ] 기록 종류 라벨 구현
- [ ] 기록 종류 선택 버튼 구현
- [ ] 내용 작성 TextField UI 구현

## 📸 Screenshot

<img width="193" alt="image" src="https://github.com/ProjectInTheClass/ReadLog/assets/26588989/e8664f8b-670c-4959-af88-6cd100ce3987">
