### ISSUE TITLE
[FEAT] 홈화면 Carousel 조금 더 자연스럽게 수정 + 서재탭에서 탭뷰로 전환되게끔 수정

### ISSUE THREAD

**Issue by rfvtgbyh11** [ProjectInTheClass/ReadLog#58]
## 💡 Issue
홈화면과 서재탭에서 조금 더 UI가 자연스럽도록 수정한다.

## 📝  todo
- [x] 홈화면 Carousel에 애니메이션 추가 + 자연스럽게 넘어가도록 변경
- [x] 서재탭 Scroll View에서 Tab View로 변경
- [x] 홈화면 폰트 함수로 변경
