### ISSUE TITLE
[FEAT] 찜 목록 화면 구현

### ISSUE THREAD

**Issue by cactus-y** [ProjectInTheClass/ReadLog#66]
## 💡 Issue
CoreData의 DB를 참조하여 찜 목록 화면을 보여주도록 구현한다.
Toolbar에 검색 버튼을 추가하여, 해당 버튼을 누르면 BookSearchView로 넘어가게 Navigation을 설정한다.
추가로 해당하는 탭 전체의 뷰에 Navigation title에 폰트를 적용하기 위해 custom toolbar를 만든다.
이거 수정하면서 BookProfileContainer뷰의 테두리를 없애고 그림자 효과를 적용시킨다.

## 📝  todo
- [ ] CoreData 연동 찜 목록 화면 구현
- [ ] 두번째 탭 전체에 Custom toolbar 적용
- [ ] 찜 목록에서 검색 화면으로 Navigation 생성
- [ ] BookProfileContainer 테두리 없애고 그림자 효과 적용

## 📸 Screenshot

![스크린샷 2023-12-10 오후 9 34 23](https://github.com/ProjectInTheClass/ReadLog/assets/55349972/81ccdb22-a601-4322-9ead-c6274b3af149)
