### ISSUE TITLE
[FEAT] 홈 화면 시작시 화면 구현

### ISSUE THREAD

**Issue by rfvtgbyh11** [ProjectInTheClass/ReadLog#8]
## 💡 Issue
홈 화면을 시작할 때 아무 책도 없는 화면을 만들고 이벤트 처리를 한다.

## 📝  todo
- [ ] 책 리스트의 개수를 데이터에서 읽어와 숫자로 표시
- [ ] 비어있는 책 리스트를 클릭하면 검색 탭으로 넘어가도록 설정
- [ ] 메뉴를 클릭하면 메뉴 리스트를 띄우기로 설정

## 📸 Screenshot

<img width="256" alt="스크린샷 2023-11-07 오전 10 10 35" src="https://github.com/ProjectInTheClass/ReadLog/assets/60872311/2f854a85-8b08-4aa3-93a2-b47916476d03">
