### ISSUE TITLE
[FEAT] 책 제목으로 검색하는 UI 구현

### ISSUE THREAD

**Issue by cactus-y** [ProjectInTheClass/ReadLog#9]
## 💡 Issue
책 제목으로 검색하는 UI를 구현합니다.
검색 결과로 책의 표지 이미지와 책의 제목을 표시합니다.

## 📝  todo
- [x] navigationBar 구현
- [x] navigationBar에 바코드 검색 버튼 구현
- [x] 검색 키워드를 적는 TextField 구현
- [x] 검색 결과 ListView로 구현 (책 이미지 & 책 제목)

## 📸 Screenshot

<img width="233" alt="스크린샷 2023-11-07 오전 9 59 07" src="https://github.com/ProjectInTheClass/ReadLog/assets/55349972/69082a64-5520-4e4d-a0cc-b0f46c45b3d9">
